Add instruction for building release
RobotecAI/rai-rosbot-xl-demo pull request #16
Opened 2024-09-05 09:58 UTC by pijaro

2024-09-16 06:52 UTC, boczekbartek commented
Connecting the issue: https://github.com/RobotecAI/rai-rosbot-xl-demo/issues/13

2024-09-16 07:10 UTC, boczekbartek requested changes
@pijaro Thank you! I found 1 minor inconsistency in the docs. Building the project now using README. I'll approve when build is finished

2024-09-16 07:10 UTC, boczekbartek commented on README.md
> +2. `run-game-release.bash`: a bash script starting the game (release build).
I think there is a typo
```suggestion
2. `run-game-bundled.bash`: a bash script starting the game (release build).
```

2024-09-16 07:32 UTC, MagdalenaKotynia commented
@pijaro cc @boczekbartek I tried to run humble-release with command: 
`./RAIROSBotXLDemo.GameLauncher -bg_ConnectToAssetProcessor=0`
 and got the following error:
`./RAIROSBotXLDemo.GameLauncher: error while loading shared libraries: libparams.so: cannot open shared object file: No such file or directory`

2024-09-16 12:44 UTC, pijaro commented
Due to a recent fix in o3de 2409, it is now possible to use the export project script, which is way simpler.

Additionally, I've added the seedlist as a part of a patching process.

2024-09-16 12:53 UTC, pijaro commented
@MagdalenaKotynia can you make sure that every [ROS 2 gem](https://docs.o3de.org/docs/user-guide/interactivity/robotics/project-configuration/#additional-ros-2-packages-required) and [o3de requirements](https://www.docs.o3de.org/docs/welcome-guide/requirements/#linux) are installed?

2024-09-16 13:04 UTC, jhanca-robotecai commented
> @pijaro cc @boczekbartek I tried to run humble-release with command: `./RAIROSBotXLDemo.GameLauncher -bg_ConnectToAssetProcessor=0` and got the following error: `./RAIROSBotXLDemo.GameLauncher: error while loading shared libraries: libparams.so: cannot open shared object file: No such file or directory`

I had the same warning message when starting the build created for Ubuntu 2404 on Ubuntu 2204.

2024-09-16 15:04 UTC, MagdalenaKotynia commented
@pijaro I checked, ROS 2 gem and o3de requirements are installed.

2024-09-16 16:00 UTC, jhanca-robotecai approved these changes

2024-09-17 07:14 UTC, pijaro commented
@MagdalenaKotynia are you running it on u22? trying it on u24 will fail, as @jhanca-robotecai mentioned.

2024-09-17 08:57 UTC, MagdalenaKotynia commented
@pijaro Yes, I was running on u22.

2024-09-17 11:18 UTC, pijaro commented
Unfortunately, I can't reproduce it. Can you paste the output of `ldd ./RAIROSBotXLDemo.GameLauncher`?

2024-09-17 11:26 UTC, MagdalenaKotynia commented
@pijaro 
```

ldd ./RAIROSBotXLDemo.GameLauncher
./RAIROSBotXLDemo.GameLauncher: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by ./RAIROSBotXLDemo.GameLauncher)
./RAIROSBotXLDemo.GameLauncher: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by ./RAIROSBotXLDemo.GameLauncher)
./RAIROSBotXLDemo.GameLauncher: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by ./RAIROSBotXLDemo.GameLauncher)
	linux-vdso.so.1 (0x00007ffe8ed70000)
	libxcb-xkb.so.1 => /lib/x86_64-linux-gnu/libxcb-xkb.so.1 (0x00007d29d6702000)
	libxcb-xfixes.so.0 => /lib/x86_64-linux-gnu/libxcb-xfixes.so.0 (0x00007d29d66f8000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007d29d66ce000)
	libxkbcommon-x11.so.0 => /lib/x86_64-linux-gnu/libxkbcommon-x11.so.0 (0x00007d29d66c3000)
	libxkbcommon.so.0 => /lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007d29d667a000)
	libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007d29cc8c0000)
	libxcb-xinput.so.0 => /lib/x86_64-linux-gnu/libxcb-xinput.so.0 (0x00007d29d6656000)
	libnav_msgs__rosidl_typesupport_fastrtps_c.so => /opt/ros/humble/lib/libnav_msgs__rosidl_typesupport_fastrtps_c.so (0x00007d29d664a000)
	libnav_msgs__rosidl_typesupport_fastrtps_cpp.so => /opt/ros/humble/lib/libnav_msgs__rosidl_typesupport_fastrtps_cpp.so (0x00007d29cc8b1000)
	libnav_msgs__rosidl_typesupport_introspection_c.so => /opt/ros/humble/lib/libnav_msgs__rosidl_typesupport_introspection_c.so (0x00007d29cc8a6000)
	libnav_msgs__rosidl_typesupport_introspection_cpp.so => /opt/ros/humble/lib/libnav_msgs__rosidl_typesupport_introspection_cpp.so (0x00007d29cc899000)
	libnav_msgs__rosidl_typesupport_cpp.so => /opt/ros/humble/lib/libnav_msgs__rosidl_typesupport_cpp.so (0x00007d29cc891000)
	libnav_msgs__rosidl_generator_py.so => /opt/ros/humble/lib/libnav_msgs__rosidl_generator_py.so (0x00007d29cc883000)
	libnav_msgs__rosidl_typesupport_c.so => /opt/ros/humble/lib/libnav_msgs__rosidl_typesupport_c.so (0x00007d29cc87c000)
	libnav_msgs__rosidl_generator_c.so => /opt/ros/humble/lib/libnav_msgs__rosidl_generator_c.so (0x00007d29cc86b000)
	libstatic_transform_broadcaster_node.so => /opt/ros/humble/lib/libstatic_transform_broadcaster_node.so (0x00007d29cc847000)
	libtf2_ros.so => /opt/ros/humble/lib/libtf2_ros.so (0x00007d29cc7ad000)
	libmessage_filters.so => /opt/ros/humble/lib/libmessage_filters.so (0x00007d29cc7a8000)
	libtf2.so => /opt/ros/humble/lib/libtf2.so (0x00007d29cc789000)
	libtf2_msgs__rosidl_typesupport_fastrtps_c.so => /opt/ros/humble/lib/libtf2_msgs__rosidl_typesupport_fastrtps_c.so (0x00007d29cc77e000)
	libtf2_msgs__rosidl_typesupport_introspection_c.so => /opt/ros/humble/lib/libtf2_msgs__rosidl_typesupport_introspection_c.so (0x00007d29cc776000)
	libtf2_msgs__rosidl_typesupport_fastrtps_cpp.so => /opt/ros/humble/lib/libtf2_msgs__rosidl_typesupport_fastrtps_cpp.so (0x00007d29cc769000)
	libtf2_msgs__rosidl_typesupport_introspection_cpp.so => /opt/ros/humble/lib/libtf2_msgs__rosidl_typesupport_introspection_cpp.so (0x00007d29cc75c000)
	libtf2_msgs__rosidl_typesupport_cpp.so => /opt/ros/humble/lib/libtf2_msgs__rosidl_typesupport_cpp.so (0x00007d29cc754000)
	libtf2_msgs__rosidl_generator_py.so => /opt/ros/humble/lib/libtf2_msgs__rosidl_generator_py.so (0x00007d29cc749000)
	libtf2_msgs__rosidl_typesupport_c.so => /opt/ros/humble/lib/libtf2_msgs__rosidl_typesupport_c.so (0x00007d29cc742000)
	libtf2_msgs__rosidl_generator_c.so => /opt/ros/humble/lib/libtf2_msgs__rosidl_generator_c.so (0x00007d29cc731000)
	libackermann_msgs__rosidl_typesupport_fastrtps_c.so => /opt/ros/humble/lib/libackermann_msgs__rosidl_typesupport_fastrtps_c.so (0x00007d29cc72c000)
	libackermann_msgs__rosidl_typesupport_introspection_c.so => /opt/ros/humble/lib/libackermann_msgs__rosidl_typesupport_introspection_c.so (0x00007d29cc725000)
	libackermann_msgs__rosidl_typesupport_fastrtps_cpp.so => /opt/ros/humble/lib/libackermann_msgs__rosidl_typesupport_fastrtps_cpp.so (0x00007d29cc71f000)
	libackermann_msgs__rosidl_typesupport_introspection_cpp.so => /opt/ros/humble/lib/libackermann_msgs__rosidl_typesupport_introspection_cpp.so (0x00007d29cc719000)
	libackermann_msgs__rosidl_typesupport_cpp.so => /opt/ros/humble/lib/libackermann_msgs__rosidl_typesupport_cpp.so (0x00007d29cc714000)
	libackermann_msgs__rosidl_generator_py.so => /opt/ros/humble/lib/libackermann_msgs__rosidl_generator_py.so (0x00007d29cc70f000)
	libackermann_msgs__rosidl_typesupport_c.so => /opt/ros/humble/lib/libackermann_msgs__rosidl_typesupport_c.so (0x00007d29cc708000)
	libackermann_msgs__rosidl_generator_c.so => /opt/ros/humble/lib/libackermann_msgs__rosidl_generator_c.so (0x00007d29cc701000)
	libgazebo_msgs__rosidl_typesupport_fastrtps_c.so => /opt/ros/humble/lib/libgazebo_msgs__rosidl_typesupport_fastrtps_c.so (0x00007d29cc6cf000)
	libgazebo_msgs__rosidl_typesupport_fastrtps_cpp.so => /opt/ros/humble/lib/libgazebo_msgs__rosidl_typesupport_fastrtps_cpp.so (0x00007d29cc693000)
	libgazebo_msgs__rosidl_typesupport_introspection_c.so => /opt/ros/humble/lib/libgazebo_msgs__rosidl_typesupport_introspection_c.so (0x00007d29cc65d000)
	libgazebo_msgs__rosidl_typesupport_introspection_cpp.so => /opt/ros/humble/lib/libgazebo_msgs__rosidl_typesupport_introspection_cpp.so (0x00007d29cc61b000)
	libgazebo_msgs__rosidl_typesupport_cpp.so => /opt/ros/humble/lib/libgazebo_msgs__rosidl_typesupport_cpp.so (0x00007d29cc5fe000)
	libgazebo_msgs__rosidl_generator_py.so => /opt/ros/humble/lib/libgazebo_msgs__rosidl_generator_py.so (0x00007d29cc5c3000)
	libgazebo_msgs__rosidl_typesupport_c.so => /opt/ros/humble/lib/libgazebo_msgs__rosidl_typesupport_c.so (0x00007d29cc5ac000)
	libgazebo_msgs__rosidl_generator_c.so => /opt/ros/humble/lib/libgazebo_msgs__rosidl_generator_c.so (0x00007d29cc55c000)
	libcontrol_toolbox.so => /opt/ros/humble/lib/libcontrol_toolbox.so (0x00007d29cc534000)
	libcontrol_msgs__rosidl_typesupport_fastrtps_c.so => /opt/ros/humble/lib/libcontrol_msgs__rosidl_typesupport_fastrtps_c.so (0x00007d29cc506000)
	libcontrol_msgs__rosidl_typesupport_fastrtps_cpp.so => /opt/ros/humble/lib/libcontrol_msgs__rosidl_typesupport_fastrtps_cpp.so (0x00007d29cc4cf000)
	libcontrol_msgs__rosidl_typesupport_introspection_c.so => /opt/ros/humble/lib/libcontrol_msgs__rosidl_typesupport_introspection_c.so (0x00007d29cc49f000)
	libcontrol_msgs__rosidl_typesupport_introspection_cpp.so => /opt/ros/humble/lib/libcontrol_msgs__rosidl_typesupport_introspection_cpp.so (0x00007d29cc468000)
	libcontrol_msgs__rosidl_typesupport_cpp.so => /opt/ros/humble/lib/libcontrol_msgs__rosidl_typesupport_cpp.so (0x00007d29cc44d000)
	libcontrol_msgs__rosidl_generator_py.so => /opt/ros/humble/lib/libcontrol_msgs__rosidl_generator_py.so (0x00007d29cc417000)
	libsensor_msgs__rosidl_typesupport_fastrtps_c.so => /opt/ros/humble/lib/libsensor_msgs__rosidl_typesupport_fastrtps_c.so (0x00007d29cc400000)
	libsensor_msgs__rosidl_typesupport_fastrtps_cpp.so => /opt/ros/humble/lib/libsensor_msgs__rosidl_typesupport_fastrtps_cpp.so (0x00007d29cc3e4000)
	libsensor_msgs__rosidl_typesupport_introspection_c.so => /opt/ros/humble/lib/libsensor_msgs__rosidl_typesupport_introspection_c.so (0x00007d29cc3c6000)
	libsensor_msgs__rosidl_typesupport_introspection_cpp.so => /opt/ros/humble/lib/libsensor_msgs__rosidl_typesupport_introspection_cpp.so (0x00007d29cc3a5000)
	libsensor_msgs__rosidl_typesupport_cpp.so => /opt/ros/humble/lib/libsensor_msgs__rosidl_typesupport_cpp.so (0x00007d29cc398000)
	libsensor_msgs__rosidl_generator_py.so => /opt/ros/humble/lib/libsensor_msgs__rosidl_generator_py.so (0x00007d29cc378000)
	libtrajectory_msgs__rosidl_typesupport_fastrtps_c.so => /opt/ros/humble/lib/libtrajectory_msgs__rosidl_typesupport_fastrtps_c.so (0x00007d29cc36f000)
	libtrajectory_msgs__rosidl_typesupport_fastrtps_cpp.so => /opt/ros/humble/lib/libtrajectory_msgs__rosidl_typesupport_fastrtps_cpp.so (0x00007d29cc366000)
	libtrajectory_msgs__rosidl_typesupport_introspection_c.so => /opt/ros/humble/lib/libtrajectory_msgs__rosidl_ [...]

2024-10-01 08:12 UTC, boczekbartek commented
@jhanca-robotecai I think @MagdalenaKotynia errors were, as @pijaro suggested due to the wrong binary build and ros-version ~ ubuntu mismatch. It was my mistake of giving @MagdalenaKotynia the wrong binary.
For me the PR looks good now and can be merged.

2024-10-01 08:12 UTC, boczekbartek approved these changes

2024-10-01 08:18 UTC, merged